# Lecture 3.3 

## 1. Data Collection

In [1]:
!pip install beautifulsoup4

### 1.1 Requests

In [2]:
import requests

In [3]:
URL = "https://csc380.beingenfa.com/Syllabus/Key_Info.html"

In [4]:
r = requests.get(URL)

In [5]:
r.status_code

200

In [6]:
r.text

'<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>\n\n<meta charset="utf-8">\n<meta name="generator" content="quarto-1.3.361">\n\n<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">\n\n\n<title>CSC 380 – key_info</title>\n<style>\ncode{white-space: pre-wrap;}\nspan.smallcaps{font-variant: small-caps;}\ndiv.columns{display: flex; gap: min(4vw, 1.5em);}\ndiv.column{flex: auto; overflow-x: auto;}\ndiv.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}\nul.task-list{list-style: none;}\nul.task-list li input[type="checkbox"] {\n  width: 0.8em;\n  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ \n  vertical-align: middle;\n}\n</style>\n\n\n<script src="../site_libs/quarto-nav/quarto-nav.js"></script>\n<script src="../site_libs/quarto-nav/headroom.min.js"></script>\n<script src="../site_libs/clipboard/clipboard.min.js"></script>\n<script src="../site

### 1.2 BeautifulSoup

In [ ]:
from bs4 import BeautifulSoup

In [7]:
soup = BeautifulSoup(r.text, 'html.parser')

In [ ]:
print(soup.prettify()) #Output cleared for web

In [ ]:
print(soup.get_text()) #Output cleared for web

In [10]:
# creating a list of all common heading tags
heading_tags = ["h1", "h2", "h3"]
for tags in soup.find_all(heading_tags):
    print(tags.text.strip())

On this page
Syllabus (Key Info)
Description
Course Objective
Expected Learning Outcomes


## 2. Data Processing

### 2.1 Numpy

Support for large, multi-dimensional arrays and matrices, and a large collection of high-level mathematical functions to operate on these arrays.

In [11]:
import numpy as np

ndarray object: an n-dimensional array of **homogeneous** data types, with many operations being performed in
compiled code for performance

* Fixed Size
* Same type of data
* Much more effiecent mathematical operations than built in data types like lists.

numpy.dtype 
- intc (same as a C integer) and intp (used for indexing)
- int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float16, float32, float64
- complex64, complex128

**Create a numpy array**

- Conversion from other Python structures (e.g., lists, tuples)
- Built-in NumPy array creation (e.g., arange, ones, zeros, etc.)
- Reading arrays from a file.

In [12]:
np.array([2,3,1,0])

array([2, 3, 1, 0])

In [13]:
np.zeros((5, 5)) #np.zeros(shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((6, 2))#np.ones(shape)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.arange(15,5,-1) #Like range function in python

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6])

In [16]:
#Return evenly spaced numbers over a specified interval.
np.linspace(0, 100, 5) # numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

array([  0.,  25.,  50.,  75., 100.])

In [17]:
np.random.random() #Keeps changing

0.7026417115321625

In [18]:
random_obj = np.random.default_rng(seed=None) #default_rng is the recommended constructor for the random number class
random_obj.random() #changes if you do not give a seed

0.21864992820211548

In [19]:
random_obj = np.random.default_rng(seed=42) #default_rng is the recommended constructor for the random number class
random_obj.random()

0.7739560485559633

In [20]:
print("Original:\n",np.arange(9))
print("After using reshape:\n",np.arange(9).reshape(3,3))

Original:
 [0 1 2 3 4 5 6 7 8]
After using reshape:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
x = np.arange(2,10)
print(x)
x[-1]

[2 3 4 5 6 7 8 9]


9

In [22]:
x.shape = (1,3)
print(x)
x[-1] # next slide

ValueError: cannot reshape array of size 8 into shape (1,3)

In [23]:
x.shape = (2,4)
print("Array:\n",x,"\n")
print("x[-1]: ",x[0])
print("x[1,3]: ", x[0,3])

Array:
 [[2 3 4 5]
 [6 7 8 9]] 

x[-1]:  [2 3 4 5]
x[1,3]:  5


In [24]:
a = np.arange(1,11)
b = np.arange(12,22)
a+b

array([13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [25]:
a = np.arange(1,11).reshape(2,5)
b = np.arange(12,22).reshape(5,2)
result = np.dot(a,b) # To multiply two arrays
result

array([[260, 275],
       [660, 700]])

In [26]:
result.transpose()

array([[260, 660],
       [275, 700]])

In [27]:
np.linalg.inv(result) # and finally

array([[ 1.4 , -0.55],
       [-1.32,  0.52]])

### 2.2 Scipy

- built on the NumPy 
- various tools and functions for solving common problems in scientific computing.

ex: 
- Fourier Transforms (scipy.fftpack)
- Multidimensional image processing (scipy.ndimage)
- Spatial data structures and algorithms (scipy.spatial)
 ..


### 2.3 Continue our discussion on Pandas

In [28]:
import pandas as pd

In [29]:
WORLD_DATA_PATH = "spotify-top-50/data/spotify-streaming-top-50-usa.csv"

In [30]:
world_df = pd.read_csv(WORLD_DATA_PATH)

In [31]:
world_df.sample()

date  position           song         artist  popularity  \
269  2023-05-23        20  Wasted On You  Morgan Wallen          86   

     duration_ms album_type  total_tracks release_date  is_explicit  \
269       178520      album            30   2021-01-08        False   

                                       album_cover_url  
269  https://i.scdn.co/image/ab67616d0000b2737d6813...

**Q: The time range of the dataset?**

In [32]:
world_df['date'].dtype

dtype('O')

In [33]:
type(world_df['date'][0])

str

In [34]:
# Convert column date to date datatype

world_df['date'] = pd.to_datetime(world_df['date'])

In [35]:
# Q : What is the time range in which this dataset is recording top 50?
# Assume that it records everyday

world_df['date'].max(), world_df['date'].min()

(Timestamp('2023-06-27 00:00:00'), Timestamp('2023-05-18 00:00:00'))